# Generated by Django 5.0.2 on 2024-03-02 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('survival_rules', models.CharField(help_text="Règles de survie des cellules, e.g., '2,3'", max_length=255)),
                ('birth_rules', models.CharField(help_text="Règles de naissance des cellules, e.g., '3'", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_start', models.CharField(max_length=255)),
                ('turn_number', models.IntegerField()),
                ('config_end', models.CharField(max_length=255)),
                ('position_alive', models.JSONField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
