# Generated by Django 5.0.2 on 2024-03-02 16:55

from django.db import migrations

def ajouter_regle(apps, schema_editor):
    Rule = apps.get_model('game', 'Rule')  
    # Vérifie si la table est vide
    if not Rule.objects.exists():
        Rule.objects.create(
            name='Règle de base',
            description='Règle de base du jeu de la vie',
            survival_rules='2,3',
            birth_rules='3'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ajouter_regle),
    ]
